spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hujing
    url: jdbc:mysql://127.0.0.1:3306/spring-security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
  application:
    name: spring-security-test